### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [thrinkos/prj-rev-bwfs-dasmoto#3]
There are several properties shared among these 3 heading elements:

https://github.com/thrinkos/prj-rev-bwfs-dasmoto/blob/4c89a00c4b61800872dc7be3a467948f5e40de0c/Dasmoto's%20Arts%20and%20Crafts/style.css#L12-L34

To avoid repetition, you could factor them out and specify them all at once by using commas to separate the selectors:
```css
.brushes, .artframes, .paint {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
